spring.application.name=cmms-application
spring.datasource.url=jdbc:postgresql://localhost:5432/eventdrivencmms
spring.datasource.username=postgres
spring.datasource.password=postgres
logging.level.dadeAndisheNiroo=DEBUG
spring.flyway.baseline-on-migrate=false
spring.flyway.enabled=true
spring.flyway.clean-disabled=false
logging.level.org.flywaydb=DEBUG
logging.level.org.flywaydb.core=DEBUG
logging.level.org.springframework.core.env=DEBUG
spring.flyway.locations=classpath:db/migration